### ISSUE TITLE
High "timeAcquiringMicros"

### ISSUE THREAD

**Issue by jimmiebtlr** [sunnykrGupta/gke-mongodb-shards#1]
We're testing a setup based on this, with I think the only real change being the storage size is 100gb for the shards and they're XFS filesystem type.

Most queries are blazing fast.

Some queries are taking awhile in multiples of 4s.  We have a clear clustering of queries in the <50ms range, ~4s, and ~8s.  The logs are showing "timeAcquiringMicros" as a relatively high value.

eg
timeAcquiringMicros: { r: 1011415 }

I'm wondering if you have any ideas what would cause that or how to approach it?

**Comment by sunnykrGupta** [comment]
Sorry for delay in response. I have not faced this before.

I think you must have figured out by now, "timeAcquiringMicros" is wait time to get lock. This happen due to full collection scans probably due to poor indexing on target fields, also data for query cannot fit into RAM and being paged in from disk. 

Turning ON logs for debugging and enabling profiling can be useful to catch slow queries hitting DB.
Make sure your StatefulSets has sufficient memory even after indexing.
Go with faster disk to server high IOPS queries.

Reference: https://lamada.eu/blog/2016/11/08/troubleshooting-mongodb-queries-performance/ Might help.

**Comment by jimmiebtlr** [comment]
Thanks for the reply, I'm not entirely sure what was going on but a restart of the cluster fixed it.

I think it may have had trouble building the indexes when it first loaded and I may not have triggered a rebuild of the indexes properly across all the stateful sets.

**Comment by sunnykrGupta** [comment]
Building index in background might be helpful when adding new field after loading dataset. Glad issue is fixed. :)
